### ISSUE TITLE
[DISCUSSION] Rewriting User Guide

### ISSUE THREAD

**Issue by C-likethis123** [AY1920S1-CS2103T-T13-1/main#110]
This is a discussion on how we can divide the workload for the user guide, and how we can rewrite the user guide to improve readability. 

**Current issue**
Currently, the user guide format is based off the AB3 User Guide. AB3 commands are short and simple, so the user guide format is okay for AB3. ORGANice has longer commands and more features. Using that format results in a messy user guide.

**Proposed change**
I suggest that the user guide could be written like it is talking to the user. 
Eg: Let's say you want to add the following patient to ORGANice.... Type the command in the command box. 

Also, each command should be accompanied by steps. 
Eg: 
1. Type xxx in the command box
2. Press 'Enter' 
3. The xxx will now be added to the list, which can be seen in the display box. 
4. If the command format is wrong, xxx happens

If any of you have any points, feel free to comment below.

**Comment by TheRealRavager** [comment]
Related to #104

**Comment by C-likethis123** [comment]
Closed as we have reached a consensus on how to author our user guides.
