### ISSUE TITLE
Package the persons folder

### ISSUE THREAD

**Issue by SimNee** [AY1920S1-CS2103T-T13-1/main#112]
Packaging the persons classes (ie, Donor, Patient, Doctor) separate from the persons fields (ie, Age, NRIC etc)

**Comment by TheRealRavager** [comment]
The proposed structure is all persons will be packaged under `organice.model.person` and all person and person child class attributes will be packaged under `organice.model.person.attributes`. The package name `attributes` is open for discussion. Possible alternatives would be `fields`
