### ISSUE TITLE
Change dummy data being displayed

### ISSUE THREAD

**Issue by C-likethis123** [AY1920S1-CS2103T-T13-1/main#144]
For a new user to ORGANice, a new addressbook.json file will be created. I suggest that the dummy data in the file should be changed. Currently they are all doctors.

**Comment by TheRealRavager** [comment]
I believe it has been changed to organice.json? Need to check. But I agree, should update dummy data

**Comment by C-likethis123** [comment]
@TheRealRavager On my side, it is still addressbook.json. Did you merge in any changes in references?

**Comment by C-likethis123** [comment]
Closed because #157 is merged into master
