### ISSUE TITLE
Remove the Delete Command from ORGANice

### ISSUE THREAD

**Issue by C-likethis123** [AY1920S1-CS2103T-T13-1/main#147]
Put as high priority because it is not an intended feature. Expected completion time should be a day maximum.

**Comment by SimNee** [comment]
Can we not delete this delete command, since the done command is also needed and it is something like delete?

**Comment by C-likethis123** [comment]
Closed as we have agreed to bring back the 'Delete' command. 

Initially, we deleted the 'Delete' feature because we did not want users to permanently delete data. In actual hospitals, even after patients/donors have been matched, their records are still kept in databases so hospitals can keep records on which patients/donors they treated before. 

However, after the PE and discussion with our teammates, we decided that the 'Delete' command should be brought back so users can delete erroneous input.
