### ISSUE TITLE
Travis may not be working

### ISSUE THREAD

**Issue by TheRealRavager** [AY1920S1-CS2103T-T13-1/main#26]
Pull requests #18 #25 seem to have Travis running for an abnormally long time.

[This](https://github.com/travis-ci/travis-ci/issues/10204) post offers a possible explanation.

**Comment by TheRealRavager** [comment]
#27 is just recently made and does not seem to suffer from this issue. I propose we close #18 and #25 then create new PRs and we don't fix this unless it pops up again.

**Comment by TheRealRavager** [comment]
If at least 2 people agree I'll mark this issue as `won't fix` and close it

**Comment by TheRealRavager** [comment]
@SimNee @WilliamRyank your PRs are affected by this I think both of you should make the call

**Comment by WilliamRyank** [comment]
@TheRealRavager im fine with closing this issue, for now just remake PR
