### ISSUE TITLE
Implement Finding Feature 

### ISSUE THREAD

**Issue by C-likethis123** [AY1920S1-CS2103T-T13-1/main#69]
As a user, I want to find potential donors for a patient so I can help the patient find a donor as fast as possible.

@TheRealRavager Previously, I think this feature was assigned to you. See if you want to track your progress of this feature with this issue or if you want to make further changes.

**Comment by TheRealRavager** [comment]
Desc is WIP:

CREATE SEARCHABLE INTERFACE (what to search by)

- [ ]`find`

- [ ] `find all`

- [ ] Automatic Find on wrong input
`e.g edit /n Jonh`
`Did you mean
1. John Smith
2. John Doe
3. Roti John`

**Comment by TheRealRavager** [comment]
Ideas:
- Edit `NameContainsKeywordsPredicate` class to detect prefixes.
- Edit `#test` to perform fuzzy searching
