### ISSUE TITLE
Change Typical Persons Naming Format

### ISSUE THREAD

**Issue by TheRealRavager** [AY1920S1-CS2103T-T13-1/main#91]
Now that we have multiple types of persons, I think it would be best to change the test persons in `testutil/TypicalPersons.java` to follow this format: `PERSONTYPE_NAME` e.g. `DONOR_JOHN`. This will eliminate ambiguity and group people by type.

Please discuss.

**Comment by C-likethis123** [comment]
I think this change is good. It allows us to see the person types.
